name: BGP-CHN List Update

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate chnbgp.list
      run: |
        # Time set
        export TZ="Asia/Shanghai"
        current_time=$(date +"# Update Time: %m/%d/%Y %H:%M:%S")
        unset TZ
        echo "$current_time" > chnbgp.list

        curl -sSL https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt | head -n 1 >> chnbgp.list
        echo "# Total: 0" >> chnbgp.list
        echo "" >> chnbgp.list
        curl -sSL https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt | tail -n +3 | sed 's/^/IP-CIDR,/' >> chnbgp.list

        curl -sSL https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt | sed 's/^/IP-CIDR6,/' >> chnbgp.list

        line_count=$(tail -n +5 chnbgp.list | wc -l)
        sed -i "3s/.*/# Total: $line_count/" chnbgp.list

        echo "Total content lines (excluding header and blank): $line_count"

    - name: Commit and push updates
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update chnbgp.list"
            git push
          else
            echo "No changes."
          fi
