name: Main Filter Files (C3) Update

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update_filters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and edit Filter files
        run: |
          # Definition of the list of files to be processed
          files=("Apple.list" "GitHub.list" "Microsoft.list" "Global.list" "GlobalMedia.list")
          # Get GMT+8 time update, formatted as MM/DD/YYYY HH:MM:SS.
          update_time=$(TZ='Asia/Shanghai' date '+%m/%d/%Y %H:%M:%S')
          for file in "${files[@]}"; do
            echo "正在处理 ${file}..."
            url="https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Surge/${file}"
            {
              echo "# Update Time: $update_time"
              curl -sSL "$url" | sed -e 's/,no-resolve//g' -e 's/规则名称/Ruleset Name/g' -e 's/规则统计/Total/g' -e 's/GlobalMedia/Streaming/g' -e 's/Global/International/g'
            } > "$file"
          done

          mv Global.list International.list
          mv GlobalMedia.list Streaming.list

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Filter Files"
            git push
          else
            echo "No changes."
          fi
