name: Main Filter Files (B7) Update

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update_filters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download China_All.list
        run: |
          curl -sS https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All.list -o China_All.list
      - name: Download Cloudflare.list
        run: |
          curl -sS https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Cloudflare/Cloudflare.list -o Cloudflare.list
      - name: Download GlobalMedia_All.list
        run: |
          curl -sS https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GlobalMedia/GlobalMedia_All.list -o GlobalMedia_All.list

      - name: Edit Files
        run: |
          ts="$(TZ='Asia/Shanghai' date '+%m/%d/%Y %H:%M:%S')"
          # China
          grep -Ev 'AUTHOR:|REPO:|UPDATED:|DOMAIN:|DOMAIN-KEYWORD:|DOMAIN-SUFFIX:|IP-CIDR:|IP-CIDR6:|USER-AGENT:' China_All.list \
            | sed -e 's/NAME:/Ruleset Name:/g' -e 's/TOTAL:/Total:/g' -e 's/,no-resolve//g'> temp && echo "# Update Time: $ts" | cat - temp > China.list
          # Cloudflare
          grep -Ev 'AUTHOR:|REPO:|UPDATED:|DOMAIN:|DOMAIN-KEYWORD:|DOMAIN-SUFFIX:|IP-CIDR:|IP-CIDR6:|USER-AGENT:' Cloudflare.list \
            | sed -e 's/NAME:/Ruleset Name:/g' -e 's/TOTAL:/Total:/g' -e 's/,no-resolve//g'> temp && echo "# Update Time: $ts" | cat - temp > Cloudflare.list
          # Streaming
          grep -Ev 'AUTHOR:|REPO:|UPDATED:|DOMAIN:|DOMAIN-KEYWORD:|DOMAIN-SUFFIX:|DESCRIPTION:|IP-CIDR:|IP-CIDR6:|PROCESS-NAME:|URL-REGEX:|USER-AGENT:' GlobalMedia_All.list \
            | sed -e 's/NAME:/Ruleset Name:/g' -e 's/TOTAL:/Total:/g' -e 's/,no-resolve//g'> temp && echo "# Update Time: $ts" | cat - temp > Streaming.list

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update Filter Files"
            git push
          else
            echo "No changes."
          fi
